language: node_js
node_js:
  - 16
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: release
    node_js: 16
    script: echo deploying...
    deploy:
    - provider: script
      script: npx semantic-release --branches develop
      on:
        branch: develop
stages:
- test
- name: release
  if: type != pull_request AND branch = develop
